ci: add weekly `flake.lock` update
eneoli/flakeshot pull request #120
Opened 2024-02-11 12:03 UTC by TornaxO7

Keeps the `flake.lock` up to date

2024-02-12 16:43 UTC, eneoli requested changes

2024-02-12 16:43 UTC, eneoli commented on .github/workflows/upate-flake-lock.yaml
> +        uses: DeterminateSystems/nix-installer-action@main
We have Nix already in our ci

2024-02-13 13:17 UTC, TornaxO7 commented
I'm unsure how to test this. But otherwise I think it should be fine.

2024-05-21 17:16 UTC, eneoli approved these changes

2024-05-21 17:16 UTC, merged