adding `apps` and `overlay` attributes to `flake.nix`
eneoli/flakeshot pull request #26
Opened 2023-11-11 00:32 UTC by TornaxO7

2023-11-11 02:25 UTC, eneoli requested changes

2023-11-11 02:25 UTC, eneoli commented on flake.nix
> +        flameshot = prev.callPackage mkFlakeshot { };
flakeshot

2023-11-11 10:01 UTC, TornaxO7 commented on flake.nix
> +        flameshot = prev.callPackage mkFlakeshot { };
*ooof*... fixed!

2023-11-12 23:24 UTC, eneoli requested changes

2023-11-12 23:24 UTC, eneoli commented on flake.nix
> +          description = "A screenshot tool for wayland and xorg!";
xorg or x11?

2023-11-12 23:47 UTC, TornaxO7 commented on flake.nix
> +          description = "A screenshot tool for wayland and xorg!";
fixed => `x11`

2023-11-12 23:54 UTC, eneoli approved these changes

2023-11-12 23:55 UTC, merged