DRAFT: Feature/wayland backend
eneoli/flakeshot pull request #29
Opened 2023-11-12 03:33 UTC by eneoli

2023-11-18 14:41 UTC, TornaxO7 requested changes

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/mod.rs
> +        state.next_screen(); // reset current screenshot metadata
Ok, so in general I'd change the code format a bit in the loop to
get a better overview of what is happening in the loop:
```suggestion
        let img = {
            let output = {
                let state = &mut *state_mutex.lock().unwrap();
                &state.outputs[i].clone()
            };

            let frame = screenshot_manager.capture_output(0, &output.output, &queue_handle, ());

            // spin until screenshot ready
            await_queue_events(
                |state| state.current_frame.is_some(),
                queue_mutex.clone(),
                state_mutex.clone(),
            )
            .await?;

            let (width, height, stride, format) = {
                let state = &mut *state_mutex.lock().unwrap();

                let current_frame = state
                    .current_frame
                    .as_ref()
                    .ok_or(WaylandError::BrokenState("current_frame"))?;

                let format = current_frame.format.ok_or(WaylandError::MissingFormat)?;

                let width = current_frame.width;
                let height = current_frame.height;
                let stride = current_frame.stride;

                (width, height, stride, format)
            };

            let img_bytes = {
                let img_bytes = vec![];
                let mut shared_memory = {
                    let state = &mut *state_mutex.lock().unwrap();

                    WaylandSharedMemory::new(
                        state.wl_shm.as_ref().ok_or(WaylandError::NoShmBind)?,
                        &queue_handle,
                        width,
                        height,
                        stride,
                        format,
                    )?
                };

                frame.copy(shared_memory.get_buffer());

                // spin until screenshot copied into shared buffer
                await_queue_events(
                    |state| state.screenshot_ready,
                    queue_mutex.clone(),
                    state_mutex.clone(),
                )
                .await?;

                shared_memory.get_memfile().read_to_end(&mut img_bytes)?;
                shared_memory.destroy();

                img_bytes
            };

            image_from_wayland(img_bytes, width, height, format)?
        };

        let output_info = OutputInfo::try_from({
            let state = &mut *state_mutex.lock().unwrap();
            &state.outputs[i].clone()
        })?;

        screenshots.push((output_info, img));

        let state = &mut *state_mutex.lock().unwrap();
        state.next_screen(); // reset current screenshot metadata
```

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/mod.rs
Ok, so in general there are two, except the suggestions below, things which bother me:

1. Those additional `await_queue_events` like this block:
  ```rust
      // spin util we got all outputs from wayland
      await_queue_events(
          |state| state.outputs_fetched,
          queue_mutex.clone(),
          state_mutex.clone(),
      )
      .await?;
  ```
  It bothers me a bit, that there are 3 cases where you have to add those "waiting-guards" otherwise I assume you'll run into
  some *runtime*-problems if those blocking code blocks aren't there. It would be nice in general to wrap those in a function,
  which, like in this example, fetches the outputs for you *and* loops for you.

2. The `WaylandScreenshotState`:
  Ok maybe it's just me, but I'm not such a fan of a global state.

  What I could imagine, but this *might* be overkill here, although this solution is maybe more
  beautiful in my opinion:

  ```rust
  pub trait FlakeshotWaylandState {
    type PollValue;

    fn finished(&self) -> bool;

    fn blocked_poll(
      &self,
      queue_mutex: Arc<Mutex<EventQueue<T>>>,
      state_mutex: Arc<Mutex<T>>,
    ) -> anyhow::Result<()> {
      let timeout_result = tokio::time::timeout(
          Duration::from_secs(120),
          tokio::spawn(async {
            let queue = &mut *queue_mutex.lock().unwrap();
            let state = &mut *state_mutex.lock().unwrap();

            while !self.finished() {
                queue.blocking_dispatch(state)?;
            }

            Ok(())
          }),
      )
      .await;

      match timeout_result {
          Ok(Ok(Ok(()))) => Ok(()),
          Ok(Ok(Err(err))) => Err(WaylandError::EventQueuePollingError(err).into()),
          Ok(Err(err)) => Err(WaylandError::ThreadSpawnFailed(err).into()),
          Err(_) => Err(WaylandError::EventQueueTimeout.into()),
      }
    }
  }
  ```

  and then you can implement a struct for example for the output-fetching:
  ```rust
  struct OutputFetcher {
    /// bla bla
  }

  impl FlakeshotWaylandState {
    fn finished(&self) -> bool {
      // bla bla
    }
  }
  ```

  and in the source code you may be able to do:

  ```rust
  let outputs = {
    let fetcher OutputFetcher::new();
    fetcher.blocked_poll(...)?;
    fetcher.get_result()
  };
  ```

  ok. To be fair this doesn't look that good as well, but this was my first thought, so maybe there
  is an actual beautiful solution to this.

But I also may have to say, that I might overengineer this of course.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_error.rs
I'd rename this file to `error.rs` since the directory is already called `wayland` we already know, what kind of errors this contains.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_frame_meta.rs
Also maybe rename this to `frame_meta.rs`

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_geometry.rs
Rename file to `geometry.rs`.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_output_info.rs
Rename this file to `output_info.rs`.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_output_mode.rs
Rename this file to `output_mode.rs`.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_screenshot_state.rs
Rename this to `screenshot_state.rs`.

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_screenshot_state.rs
> +     */
```suggestion
    /// Resets state to before a screenshot was made.
```

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_screenshot_state.rs
> + */
```suggestion
// Globals as advertised by the Wayland compositor.
```

2023-11-18 14:41 UTC, TornaxO7 commented on src/backend/wayland/wayland_shared_memory.rs
Rename this to `shared_memory.rs`.

2023-11-18 15:13 UTC, eneoli commented on src/backend/wayland/wayland_error.rs
I'm strongly against removing the Wayland prefix. In larger projects file search is entirely made by globally searching by file name instead of navigating through directories. In fact when renaming we would have duplicated file names.

2023-11-18 15:13 UTC, eneoli commented on src/backend/wayland/wayland_frame_meta.rs
s.o.

2023-11-18 15:14 UTC, eneoli commented on src/backend/wayland/wayland_geometry.rs
s.o.

2023-11-18 15:14 UTC, eneoli commented on src/backend/wayland/wayland_output_info.rs
s.o.

2023-11-18 15:15 UTC, eneoli commented on src/backend/wayland/wayland_output_mode.rs
s.o.

2023-11-18 15:16 UTC, eneoli commented on src/backend/wayland/wayland_shared_memory.rs
s.o.

2023-11-18 15:16 UTC, eneoli commented on src/backend/wayland/wayland_screenshot_state.rs
s.o.

2023-11-18 18:12 UTC, eneoli commented on src/backend/wayland/mod.rs
> +    await_queue_events(
wait_until is to generic. It does not state that we poll events. In fact await_queue_events can also be there without the comment

2023-11-18 18:12 UTC, eneoli commented on src/backend/wayland/mod.rs
> +        await_queue_events(
s.o.

2023-11-18 18:24 UTC, eneoli commented on src/backend/wayland/mod.rs
This is in my opinion to over engineered and does not fix your point: we still have the blocked_poll. What we need are some methods that capsule a action following the await polling block.

For example:

`

trigger_screenshot(...);

await_queue_events(
        |state| state.screenshot_ready,
        queue_mutex.clone(),
        state_mutex.clone(),
    )
    .await?;`

Should be replaced with

`
take_screenshot().await;
`

The take_screenshot function will encapsulate the two code blocks and we will be use the pros of async code and hide the ugly polling logic behind an async api. 

Seondly, you're talking about global states. I don't consider the wayland_screenshot_state a global state. It encapsulates all logic that is need for a screenshot and thus represents a logical unit. I don't see any benefits of splitting the state into more sub states.

2023-11-20 13:45 UTC, TornaxO7 requested changes
Some little suggestions.

2023-11-20 13:45 UTC, TornaxO7 commented on src/backend/wayland/mod.rs
> +        shared_memory.destroy();
```suggestion
        let img = {
            let shared_memory = {
              let frame = {
                let output = &manager.get_outputs()?[i];
                screenshot_manager.capture_output(0, &output.output, &queue_handle, ())
              };

              let mut shared_memory = manager.create_shared_memory()?;
              frame.copy(shared_memory.get_buffer());
              manager.await_screenshot()?;

              shared_memory
            };

            let mut screenshot_data = vec![];
            shared_memory.get_memfile().read_to_end(&mut data)?;

            let width = shared_memory.width();
            let height = shared_memory.height();
            let format = shared_memory.format();

            let image = image_from_wayland(screenshot_data, width, height, format)?;

            shared_memory.destroy();
            image
        };

        let output_info = OutputInfo::try_from({ &manager.get_outputs()?[i] })?;

        screenshots.push((output_info, img));
```

2023-11-20 13:45 UTC, TornaxO7 commented on src/backend/wayland/wayland_screenshot_state.rs
> +
```suggestion
```
(Why not removing this?)

2023-11-20 16:40 UTC, TornaxO7 submitted a review, later dismissed
:peepoYes:

2023-11-20 17:10 UTC, TornaxO7 submitted a review, later dismissed

2023-11-20 17:16 UTC, TornaxO7 approved these changes
![peepoPray](https://github.com/eneoli/flakeshot/assets/50843046/7a229304-1880-4617-889b-166d243d2363)

2023-11-20 17:17 UTC, merged