DRAFT: Feature/UI
eneoli/flakeshot pull request #54
Opened 2023-12-20 00:57 UTC by eneoli

Closes #5

2023-12-30 00:51 UTC, eneoli commented
We will implement basic cropping in the next iteration as this MR is already quite large and we can distribute work better this way.

@TornaxO7  This PR is blocked until #58 is resolved.

2023-12-30 14:56 UTC, eneoli commented
Things done:

- added ui (fullscreen windows that show screenshots)
- added toolbar
- added file chooser
- replaced anyhow with thiserror in wayland backend

2023-12-31 00:14 UTC, TornaxO7 requested changes
In general, I'd, if it's possible, use anyhows `with context` because it's error output is better formatted than from `expected`.

2023-12-31 00:14 UTC, TornaxO7 commented on src/frontend/ui_manager.rs
> +                    .expect("Couldn't save image.");
maybe make use of anyhows `with_context` here instead of `expect`?

2023-12-31 00:14 UTC, TornaxO7 commented on src/frontend/ui/canvas.rs
> +            .expect("Couldn't create image from buffer");
maybe using anyhows `with_context` instead of `expect`

2023-12-31 00:14 UTC, TornaxO7 commented on src/frontend/main_window.rs
> +        let mut model = Self::init(total_width, total_height);
```suggestion
        let mut model = {
            let (total_width, total_height) = get_total_view_size(&monitors.values().collect());
            Self::init(total_width, total_height)
        };
```

2023-12-31 00:21 UTC, eneoli commented on src/frontend/file_chooser.rs
> +    on_submit: Box<dyn Fn(Option<String>) -> ()>,
We could but why should we?

2024-01-02 17:34 UTC, TornaxO7 requested changes

2024-01-02 17:34 UTC, TornaxO7 commented on src/frontend/ui/canvas.rs
> +    }
I'd actually replace this part with something similar to [this](https://github.com/eneoli/flakeshot/blob/main/src/backend/x11.rs#L134-L139).

2024-01-02 22:21 UTC, TornaxO7 requested changes
One last thing

2024-01-03 00:25 UTC, TornaxO7 approved these changes

2024-01-03 00:26 UTC, merged