81 implent ipc instant clipboard
eneoli/flakeshot pull request #90
Opened 2024-01-30 12:39 UTC by TornaxO7

supercedes https://github.com/eneoli/flakeshot/pull/87 because we are going to insert the screenshot immediately into clipboard/a file.

2024-01-30 12:43 UTC, TornaxO7 commented
@eneoli nvm the review, I forgot some other stuff...

2024-02-03 06:05 UTC, TornaxO7 commented
@eneoli One big point which is missing, is the auto-exit if you clicked on the clipboard-button. But I'd like to create another PR for that since this PR is already big enough, in my opinion. Do you agree?

2024-02-03 14:39 UTC, eneoli commented
@TornaxO7 is this ready for review?

2024-02-03 14:40 UTC, TornaxO7 commented
> @TornaxO7 is this ready for review?

aye

2024-02-03 14:41 UTC, eneoli commented
But the pipeline is failing @TornaxO7

2024-02-03 14:48 UTC, TornaxO7 commented
> But the pipeline is failing @TornaxO7

fixed

2024-02-03 22:46 UTC, eneoli requested changes

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +            mode: cmd,
```suggestion
    fn init(total_width: i32, total_height: i32, cli_command: cli::Command) -> Self {
        AppModel {
            ui_manager: UiManager::new(total_width, total_height),
            window_senders: vec![],
            cli_comand,
```

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +    mode: cli::Command,
or create an extra enum if you don't want to expose the command.

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +                )
```suggestion

                (format!("{}", err), Hint::Urgency(notify_rust::Urgency::Critical))
```

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +                        })
```suggestion
                        .map_err(|err| error!("An error occured while trying to send a notification: {}", err ))
```

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> -        window.hide();
why?

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +        _root: Self::Root,
this should cause an error. Thats not how it is defined in the trait

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +                .map(|s| s.to_string()),
this will notify on any tool event

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +                .map(|s| s.to_string()),
Decouple from tool events.

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +        let mut monitors = get_monitors();
now the monitors are fetched twice....

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +                cli::Command::Gui => std::process::exit(0),
This won't do a clean shutdown. iirc there is something similar via `relm4::main_application`

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +    let window2 = window.clone();
You might use `relm4::main_application`

2024-02-03 22:46 UTC, eneoli commented on src/lib.rs
> +const TMP_IMG_PATH: &str = "screenshot.png";
where is this used?

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +        use ksni::menu::*;
import statements always on top.

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +            activate: Box::new(|_| std::process::exit(0)),
this won't do a graceful exit.

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +/// Otherwise the error will be returned.
```suggestion
/// If no error occured: Returns the lock-file, otherwise `None`.
/// If an error occurs the error will be returned.
```

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +/// Otherwise the error will be returned.
>If no error occured: Returns the lock-file (if available)

Does it return the lock-file or not? Ambiguous.

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +    };
```suggestion
    };

```

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
>          }
ui mixed with cli

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +        let mut monitors = get_monitors();
mixed with cli

2024-02-03 22:46 UTC, eneoli commented on src/frontend/main_window.rs
> +            });
```suggestion
            });

```

2024-02-03 22:46 UTC, eneoli commented on src/lib.rs
> +}
Where is this used?

```suggestion
```

2024-02-03 22:46 UTC, eneoli commented on src/lib.rs
> +const TMP_IMG_PATH: &str = "screenshot.png";
```suggestion
```

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +        if daemon_already_exists {
```suggestion
        let tray_already_exists = err == rustix::io::Errno::WOULDBLOCK;

        if tray_already_exists {
```

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +        if daemon_already_exists {
In fact the whole application is running already no?

2024-02-03 22:46 UTC, eneoli commented on src/tray/mod.rs
> +const LOCK_FILE: &str = "tray.lock";
In fact the whole application is running no? If so then maybe

```suggestion
const LOCK_FILE: &str = "flakeshot.lock";
```

2024-02-03 22:49 UTC, eneoli commented on src/tray/mod.rs
> +const LOCK_FILE: &str = "tray.lock";
btw what happens if `flakeshot tray`is running and I run `flakeshot gui`?

2024-02-05 17:46 UTC, eneoli commented on src/frontend/main_window.rs
> -        window.hide();
deprecated

2024-02-07 17:48 UTC, closed without merging